name: enkel_chat
description: En enkel chat Flutter applikasjon.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  image_picker: ^0.7.3
  timeago: any

  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  path: ^1.8.0
  meta: ^1.3.0
  equatable: ^2.0.0

  cloud_firestore: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true